// Shared type contract for the whole app.
//
// OWNED BY THE ORCHESTRATOR. Do not edit this file in a feature workstream —
// if you need a change here, say so in your report instead. Everything else
// imports from `@/types` so the engine, storage and sync layers can be built
// independently against one stable contract.

import type { StateCode } from '../data/states';
import type { CategoryId } from '../data/categories';

export type { StateCode, CategoryId };

/* ────────────────────────────── questions ────────────────────────────── */

export type OptionKey = 'a' | 'b' | 'c' | 'd';

export const OPTION_KEYS: readonly OptionKey[] = ['a', 'b', 'c', 'd'] as const;

export type QuestionId = string;

export interface QuestionOptions {
  readonly a: string;
  readonly b: string;
  readonly c: string;
  readonly d: string;
}

/** A question exactly as it appears in `src/data/questions.json`. */
export interface Question {
  readonly id: QuestionId;
  readonly number: number;
  readonly scope: 'federal' | 'state';
  /** Set iff `scope === 'state'`. */
  readonly state?: StateCode;
  readonly question: string;
  readonly options: QuestionOptions;
  readonly solution: OptionKey;
  readonly category: CategoryId;
  readonly explanation: string;
  /** Repo-relative, e.g. `"img/f085.jpg"`. Absent when the question has no image. */
  readonly image?: string;
  /** Upstream sha256 id, for traceability back to the source dataset. */
  readonly sourceId: string;
}

/** One question's translation, from `src/data/i18n/questions.<lang>.json`. */
export interface QuestionTranslation {
  readonly question: string;
  readonly options: QuestionOptions;
  readonly explanation: string;
}

export type QuestionTranslations = Readonly<Record<QuestionId, QuestionTranslation>>;

/* ───────────────────────────── curriculum ───────────────────────────── */

export interface Level {
  readonly id: string;
  /** Display label, e.g. `"3.2"`. */
  readonly label: string;
  /** Short English name; translated at render time via the UI locale. */
  readonly name: string;
  readonly questionIds: readonly QuestionId[];
  /** Boss levels force recall-first and disable hints. */
  readonly boss: boolean;
}

export interface World {
  readonly id: string;
  readonly index: number;
  readonly name: string;
  /** Present for the 10 federal worlds; absent for the generated Heimat world. */
  readonly category?: CategoryId;
  /** True for the per-state Heimat world, which is always unlocked. */
  readonly heimat: boolean;
  readonly levels: readonly Level[];
}

export interface Curriculum {
  readonly worlds: readonly World[];
}

/* ────────────────────────────── progress ────────────────────────────── */

/**
 * Per-question progress. Keyed by question id, which already encodes the state
 * (`BW03`), so federal progress is shared across states automatically and each
 * state's progress is namespaced. Switching state never destroys progress.
 *
 * Every field must be mergeable without a UI prompt — see `src/lib/sync/merge.ts`.
 */
export interface QuestionProgress {
  readonly seen: number;
  readonly correct: number;
  readonly wrong: number;
  readonly consecutiveCorrect: number;
  readonly hintsUsed: number;
  /** Epoch ms, or 0 when never seen. */
  readonly lastSeen: number;
  /** SM-2-lite ease factor. */
  readonly ease: number;
  /** Epoch ms when this question is next due. */
  readonly dueAt: number;
  readonly flagged: boolean;
  readonly note: string;
  /** Epoch ms of the last local write. Drives last-write-wins fields on merge. */
  readonly updatedAt: number;
}

export type MasteryBucket = 'new' | 'learning' | 'familiar' | 'mastered';

/* ────────────────────────────── sessions ────────────────────────────── */

export type SessionMode = 'learn' | 'drill' | 'mock' | 'speed' | 'reverse';

export interface AnswerRecord {
  readonly questionId: QuestionId;
  readonly chosen: OptionKey | null;
  readonly correct: boolean;
  readonly hintsUsed: number;
  readonly ms: number;
}

/** A completed session. Unioned by `id` on merge, never overwritten. */
export interface SessionResult {
  readonly id: string;
  readonly mode: SessionMode;
  readonly levelId?: string;
  /** Which state the session was taken under. */
  readonly state: StateCode;
  readonly startedAt: number;
  readonly finishedAt: number;
  readonly answers: readonly AnswerRecord[];
  readonly correct: number;
  readonly total: number;
}

/** A completed mock exam. Unioned by `id` on merge. */
export interface MockResult {
  readonly id: string;
  /** Which state the mock was taken under — mocks are state-specific. */
  readonly state: StateCode;
  readonly startedAt: number;
  readonly finishedAt: number;
  readonly durationMs: number;
  readonly answers: readonly AnswerRecord[];
  readonly correct: number;
  readonly total: number;
  readonly passed: boolean;
}

/* ────────────────────────────── settings ────────────────────────────── */

export type UiLocale = 'de' | 'en' | 'tr' | 'ru' | 'fr' | 'ar' | 'uk' | 'hi';
export type TranslationLocale = 'en' | 'tr' | 'ru' | 'fr' | 'ar' | 'uk' | 'hi';
/** `'off'` means German only. */
export type TranslationSetting = TranslationLocale | 'off';
export type ThemeSetting = 'light' | 'dark' | 'system';

export interface Settings {
  /** `null` until onboarding picks one — this is what gates the first-run wizard. */
  readonly state: StateCode | null;
  readonly uiLocale: UiLocale;
  readonly translation: TranslationSetting;
  readonly alwaysShowTranslation: boolean;
  readonly mockTranslations: boolean;
  readonly recallFirst: boolean;
  readonly tts: boolean;
  readonly ttsAutoplay: boolean;
  readonly theme: ThemeSetting;
  readonly onboarded: boolean;
  readonly updatedAt: number;
}

/* ───────────────────────── the persisted document ───────────────────── */

/** Epoch-ms day keys (`YYYY-MM-DD`) on which the user practised. */
export type PracticeDays = Readonly<Record<string, true>>;

/**
 * The entire progress blob. This is what lives in IndexedDB, what export/import
 * round-trips, and what is mirrored to Firestore as a single document.
 */
export interface ProgressDoc {
  readonly schemaVersion: number;
  readonly settings: Settings;
  readonly progress: Readonly<Record<QuestionId, QuestionProgress>>;
  readonly sessions: readonly SessionResult[];
  readonly mocks: readonly MockResult[];
  readonly practiceDays: PracticeDays;
  readonly badges: Readonly<Record<string, number>>;
  readonly xp: number;
  /** Epoch ms of the last write on this device. */
  readonly updatedAt: number;
}

/* ──────────────────────────────── sync ──────────────────────────────── */

export type SyncStatus = 'signed-out' | 'syncing' | 'synced' | 'offline' | 'error';

/**
 * A pending local mutation. The UI only ever writes locally; the outbox is
 * flushed by the adapter when online. We own the queue so the behaviour is
 * testable and adapter-agnostic.
 */
export type Mutation =
  | { readonly kind: 'progress'; readonly id: string; readonly at: number; readonly questionId: QuestionId; readonly value: QuestionProgress }
  | { readonly kind: 'settings'; readonly id: string; readonly at: number; readonly value: Settings }
  | { readonly kind: 'session'; readonly id: string; readonly at: number; readonly value: SessionResult }
  | { readonly kind: 'mock'; readonly id: string; readonly at: number; readonly value: MockResult }
  | { readonly kind: 'practiceDay'; readonly id: string; readonly at: number; readonly day: string }
  | { readonly kind: 'badge'; readonly id: string; readonly at: number; readonly badge: string; readonly earnedAt: number }
  | { readonly kind: 'xp'; readonly id: string; readonly at: number; readonly value: number };

export type Unsubscribe = () => void;

export interface SyncAccount {
  readonly uid: string;
  readonly email: string | null;
  readonly displayName: string | null;
}

export interface SyncAdapter {
  /** Stable id, e.g. `'noop'` or `'firestore'`. */
  readonly name: string;
  /** False when Firebase is unconfigured — the UI must degrade, never crash. */
  readonly configured: boolean;
  status(): SyncStatus;
  account(): SyncAccount | null;
  signIn(): Promise<void>;
  signOut(): Promise<void>;
  pull(): Promise<ProgressDoc | null>;
  push(mutations: readonly Mutation[]): Promise<void>;
  subscribe(cb: (doc: ProgressDoc) => void): Unsubscribe;
}
